version: 1.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
platform:
- win-x86-librw_d3d9-mss
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
install:
- cmd: >-
    git submodule update --init --recursive

    premake5 vs2019 --with-librw

build:
  project: build/re3.sln
  verbosity: minimal
artifacts:
- path: bin/%PLATFORM%/%CONFIGURATION%/re3.exe
  name: re3.exe
- path: bin/%PLATFORM%/%CONFIGURATION%/re3.pdb
  name: re3.pdb
