version: 1.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: Win32
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
install:
- cmd: >-
    git submodule update --init --recursive

    copy premake5.exe "librw/premake5.exe"     

    cd "librw" && premake5 vs2019 && msbuild "build/librw.sln" /property:Configuration=%CONFIGURATION% /property:Platform="win-x86-d3d9"

    cd "%APPVEYOR_BUILD_FOLDER%" && premake5 vs2019

build:
  project: build/re3.sln
  verbosity: minimal
artifacts:
- path: bin/%CONFIGURATION%/re3.exe
  name: re3.exe
- path: bin/%CONFIGURATION%/re3.pdb
  name: re3.pdb
